### ISSUE TITLE
ChatControl feature suggestion

### ISSUE THREAD

**Issue by ArtelGG** [kangarko/ChatControl-Free#345]
Would it be possible for you to add a custom formatting system for death messages?

**An example of this in the configuration:**
```
# {victim} - Self explanatory
# {attacker} - Self explanatory
# {item} - Displays the item itself
# {item-formatted} - Displays the custom name of the name, such as a lore, etc...
Messages:
  Death:
    Mob: '{victim} was slain by {attacker}'
    Player:
      Empty: '{victim} was killed by {attacker}'
      Item: '{victim} was killed by {attacker} using {item-formatted} ({item})'
```
